<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        img {
            width: 100%;
        }
    </style>
</head>

<body>
    <script>
        var pic = new Array;
        pic[0] = 'E:/lita/Im02.jpg';
        pic[1] = 'E:/lita/Im03.jpg';
        pic[2] = 'E:/lita/Im01.jpg';
        pic[3] = 'E:/lita/Im04.jpg';
        parseInt(Math.random() * (pic.length), 10);
        var choose = Math.floor(Math.random() * (pic.length));
        document.write('<img src="' + pic[choose] + ' ">');
    </script>
</body>

</html>

